apiVersion: v1
kind: Secret
metadata:
  name: env
type: Opaque
stringData:
  .env: |-
{{ .Files.Get .Values.envFile | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-service-account
type: Opaque
stringData:
  gcp-service-account.json: |-
{{ .Files.Get .Values.gcpServiceAccount | indent 4 }}
